//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while downloading the list of games..
        /// </summary>
        internal static string errorDownloadingAppList {
            get {
                return ResourceManager.GetString("errorDownloadingAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while grabbing game details..
        /// </summary>
        internal static string errorGrabbingGameDetails {
            get {
                return ResourceManager.GetString("errorGrabbingGameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local game list text file cannot be found. Please browse /GetList first..
        /// </summary>
        internal static string errorLocalGameListNotFound {
            get {
                return ResourceManager.GetString("errorLocalGameListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an appid to query game details..
        /// </summary>
        internal static string errorMissingAppId {
            get {
                return ResourceManager.GetString("errorMissingAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And error ocurred while saving game details to database..
        /// </summary>
        internal static string errorStoringGameDetailsToDb {
            get {
                return ResourceManager.GetString("errorStoringGameDetailsToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while storing game to local database..
        /// </summary>
        internal static string errorStoringGameToDb {
            get {
                return ResourceManager.GetString("errorStoringGameToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while reading local game list text file..
        /// </summary>
        internal static string errorWhileReadingLocalGameList {
            get {
                return ResourceManager.GetString("errorWhileReadingLocalGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error ocurred while writing to apps list file..
        /// </summary>
        internal static string errorWhileSavingAppsListFile {
            get {
                return ResourceManager.GetString("errorWhileSavingAppsListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (!) No games left to update..
        /// </summary>
        internal static string messageNoGamesLeftToUpdate {
            get {
                return ResourceManager.GetString("messageNoGamesLeftToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully grabbed game details..
        /// </summary>
        internal static string messageSuccessfullyGrabbedGameDetails {
            get {
                return ResourceManager.GetString("messageSuccessfullyGrabbedGameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully mined 10 more games. This page will be automatically refreshed after 15 seconds to mine next 10 games..
        /// </summary>
        internal static string messageSuccessfullyMinedRange {
            get {
                return ResourceManager.GetString("messageSuccessfullyMinedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully saved the list of games..
        /// </summary>
        internal static string messageSuccessfullySavedList {
            get {
                return ResourceManager.GetString("messageSuccessfullySavedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully stored the list of games into local database..
        /// </summary>
        internal static string messageSuccessfullyStoresListOfGamesIntoDb {
            get {
                return ResourceManager.GetString("messageSuccessfullyStoresListOfGamesIntoDb", resourceCulture);
            }
        }
    }
}
